### ISSUE TITLE
Exception at startup

### ISSUE THREAD

**Issue by TheJuffo** [igniterealtime/openfire-presence-plugin#5]
When starting Openfire with the Presence plugin deployed we sometimes get the following exception:

```
org.jivesoftware.openfire.container.PluginServlet - Exception attempting to load servlet 'PresenceStatusServlet' (org.jivesoftware.openfire.plugin.presence.PresenceStatusServlet) of plugin 'presence'
java.lang.NullPointerException: null
at org.jivesoftware.openfire.plugin.presence.PresenceStatusServlet.loadResource(PresenceStatusServlet.java:164) ~[?:?]
at org.jivesoftware.openfire.plugin.presence.PresenceStatusServlet.init(PresenceStatusServlet.java:74) ~[?:?]
at org.jivesoftware.openfire.container.PluginServlet.registerServlets(PluginServlet.java:215) [xmppserver-4.6.4.jar:4.6.4]
at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:674) [xmppserver-4.6.4.jar:4.6.4]
at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:375) [xmppserver-4.6.4.jar:4.6.4]
at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:363) [xmppserver-4.6.4.jar:4.6.4]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_302]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
```

I checked the code and it seems that it happens because it can't load an icon as a resource. No idea why. A restart of the plugin rectifies the issue.

**Comment by guusdk** [comment]
I cannot quite explain that. I have modified code to load images on demand, allowing for a retry if they initially cannot be loaded. Hopefully, that prevents the issue and/or allows it to automatically correct itself, without requiring a restart.
